name: Update Latest Blog Posts

on:
  schedule:
    - cron: '0 12 * * *'  # Daily 12:00 UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch latest posts
        uses: armingli/readme-update-actions@v2
        with:
          rss_list: "https://blog.jimmyvo.com/index.xml"
          max_post: "5"
          commit_message: "ðŸ¤– Update latest blog posts"
