name: Update Latest Blog Posts

on:
  schedule:
    - cron: '0 12 * * *'  # Daily 12:00 UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://blog.jimmyvo.com/index.xml" # Replace with your blog RSS address
          max_post_count: 3 # Sync the latest 5 articles
          readme_path: ./README.md # Target README file
          commit_message: "Update README with latest blog posts"